In [1]:
import numpy as pd
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
pd.read_csv('tmdb_5000_credits.csv')

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4808,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4809,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4810,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4811,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4812,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [5]:
credits=pd.read_csv('tmdb_5000_credits.csv')

In [6]:
credits=credits[['movie_id','title','cast','crew']]

In [7]:
movies.merge(credits, on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [8]:
movies=movies.merge(credits, on='title')

In [9]:
movies.shape

(4809, 23)

In [10]:
movies[['movie_id','title','overview','genres','keywords','cast','crew']]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [12]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   object
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4805 non-null   object
dtypes: object(7)
memory usage: 263.1+ KB

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        4
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:

movies.duplicated().sum()

np.int64(0)

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# [action,adventure,fantasy,science fiction]

In [18]:
def convert(obj):
    L=[]
    for i in obj:
        L.append(i['name'])
        return L

In [19]:
convert('genres')

TypeError: string indices must be integers, not 'str'

# it will convert list of strings into list

In [54]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [59]:
movies['genres'].apply(convert)

TypeError: string indices must be integers, not 'str'

In [ ]:
movies['genres']=movies['genres'].apply(convert)

In [56]:
movies['genres']

0       [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...
1       [[, {, ", i, d, ", :, , 1, 2, ,, , ", n, a, m,...
2       [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...
3       [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...
4       [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...
                              ...
4804    [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...
4805    [[, {, ", i, d, ", :, , 3, 5, ,, , ", n, a, m,...
4806    [[, {, ", i, d, ", :, , 3, 5, ,, , ", n, a, m,...
4807                                               [[, ]]
4808    [[, {, ", i, d, ", :, , 9, 9, ,, , ", n, a, m,...
Name: genres, Length: 4802, dtype: object

In [ ]:
movies.head()

In [57]:
movies['keywords']=movies['keywords'].apply(convert)

TypeError: string indices must be integers, not 'str'

In [58]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[John, Carter, is, a, war-weary,, former, mili..."

In [21]:
import ast
def fetch_director(obj):
    L=[]
    try:
        for i in ast.literal_eval(obj):
            if i['job']=='Director':
                L.append(i['name'])
                break
    except (SyntaxError, ValueError):
        pass  
    return L

In [22]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4802, dtype: object

In [23]:
movies['crew']

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4804    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4802, dtype: object

In [24]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4802, dtype: object

In [25]:
import ast
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
           L.append(i['name'])
           counter=counter+1
        else:
            break
    return L

In [26]:
movies['cast'].apply (convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4802, dtype: object

In [27]:
movies['cast']=movies['cast'].apply (convert3)

In [28]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [29]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4802, dtype: object

In [30]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [31]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [32]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [33]:
movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

0       [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
1       [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
2       [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
3       [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
4       [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
                              ...
4804    [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
4805    [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
4806    [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
4807    [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
4808    [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
Name: crew, Length: 4802, dtype: object

In [34]:
movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LéaSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishé, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4802, dtype: object

In [35]:
movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

0       [[, {, ", i, d, ", :, , 1, 4, 6, 3, ,, , ", n,...
1       [[, {, ", i, d, ", :, , 2, 7, 0, ,, , ", n, a,...
2       [[, {, ", i, d, ", :, , 4, 7, 0, ,, , ", n, a,...
3       [[, {, ", i, d, ", :, , 8, 4, 9, ,, , ", n, a,...
4       [[, {, ", i, d, ", :, , 8, 1, 8, ,, , ", n, a,...
                              ...
4804    [[, {, ", i, d, ", :, , 5, 6, 1, 6, ,, , ", n,...
4805                                               [[, ]]
4806    [[, {, ", i, d, ", :, , 2, 4, 8, ,, , ", n, a,...
4807                                               [[, ]]
4808    [[, {, ", i, d, ", :, , 1, 5, 2, 3, ,, , ", n,...
Name: keywords, Length: 4802, dtype: object

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."

In [37]:
movies['tags']=movies['overview']+movies['keywords']+movies['genres']+movies['cast']+movies['crew']

In [38]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[John, Carter, is, a, war-weary,, former, mili..."

In [39]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'u',
 'l',
 't',
 'u',
 'r',
 'e',
 '',
 'c',
 'l',
 'a',
 's',
 'h',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '9',
 '6',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '6',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'c',
 'o',
 'l',
 'o',
 'n',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '6',
 '7',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'c',
 'i',
 'e',
 't',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '8',
 '0',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 't',
 'r',
 'a',
 'v',
 'e',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '6',
 '8',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'i',
 's',
 't',
 'i',
 'c',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '4',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'r',
 'o',
 'm',
 'a',
 'n',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '8',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '9',
 '5',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '4',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 't',
 'r',
 'i',
 'b',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '5',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '',
 'p',
 'l',
 'a',
 'n',
 'e',
 't',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '9',
 '8',
 '7',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'g',
 'i',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '1',
 '3',
 '9',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'a',
 'r',
 'i',
 'n',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '3',
 '0',
 '6',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'l',
 'd',
 'i',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '4',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'b',
 'a',
 't',
 't',
 'l',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '7',
 '2',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'l',
 'o',
 'v',
 'e',
 '',
 'a',
 'f',
 'f',
 'a',
 'i',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '6',
 '5',
 '4',
 '3',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'n',
 't',
 'i',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '9',
 '3',
 '5',
 '5',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'p',
 'o',
 'w',
 'e',
 'r',
 '',
 'r',
 'e',
 'l',
 'a',
 't',
 'i',
 'o',
 'n',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '6',
 '6',
 '9',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'i',
 'n',
 'd',
 '',
 'a',
 'n',
 'd',
 '',
 's',
 'o',
 'u',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '9',
 '7',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 '3',
 'd',
 '"',
 '}',
 ']',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'd',
 'v',
 'e',
 'n',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'F',
 'a',
 'n',
 't',
 'a',
 's',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '8',
 '7',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 '',
 'F',
 'i',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ']',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 '[',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '2',
 'f',
 'e',
 '4',
 '8',
 '0',
 '0',
 '9',
 '2',
 '5',
 '1',
 '4',
 '1',
 '6',
 'c',
 '7',
 '5',
 '0',
 'a',
 'c',
 'a',
 '2',
 '3',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'E',
 'd',
 'i',
 't',
 'i',
 'n',
 'g',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '0',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '7',
 '2',
 '1',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 ...]

In [40]:
new_df = movies[['movie_id','title','tags']]

In [41]:
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4802, dtype: object

In [42]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\User\AppData\Local\Temp\ipykernel_13444\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [43]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [50]:
new_df['tags'].apply(lambda x:x.lower())

AttributeError: 'list' object has no attribute 'lower'

In [44]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\User\AppData\Local\Temp\ipykernel_13444\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [45]:
new_df['tags']

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4802, dtype: object

In [46]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [47]:
new_df = movies[['movie_id','title','tags']]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'u',
 'l',
 't',
 'u',
 'r',
 'e',
 '',
 'c',
 'l',
 'a',
 's',
 'h',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '9',
 '6',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '6',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'c',
 'o',
 'l',
 'o',
 'n',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '6',
 '7',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'c',
 'i',
 'e',
 't',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '8',
 '0',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 't',
 'r',
 'a',
 'v',
 'e',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '6',
 '8',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'i',
 's',
 't',
 'i',
 'c',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '4',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'r',
 'o',
 'm',
 'a',
 'n',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '8',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '9',
 '5',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '4',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 't',
 'r',
 'i',
 'b',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '5',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '',
 'p',
 'l',
 'a',
 'n',
 'e',
 't',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '9',
 '8',
 '7',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'g',
 'i',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '1',
 '3',
 '9',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'a',
 'r',
 'i',
 'n',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '3',
 '0',
 '6',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'l',
 'd',
 'i',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '4',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'b',
 'a',
 't',
 't',
 'l',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '7',
 '2',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'l',
 'o',
 'v',
 'e',
 '',
 'a',
 'f',
 'f',
 'a',
 'i',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '6',
 '5',
 '4',
 '3',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'n',
 't',
 'i',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '9',
 '3',
 '5',
 '5',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'p',
 'o',
 'w',
 'e',
 'r',
 '',
 'r',
 'e',
 'l',
 'a',
 't',
 'i',
 'o',
 'n',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '6',
 '6',
 '9',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'i',
 'n',
 'd',
 '',
 'a',
 'n',
 'd',
 '',
 's',
 'o',
 'u',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '9',
 '7',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 '3',
 'd',
 '"',
 '}',
 ']',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'd',
 'v',
 'e',
 'n',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'F',
 'a',
 'n',
 't',
 'a',
 's',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '8',
 '7',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 '',
 'F',
 'i',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ']',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 '[',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '2',
 'f',
 'e',
 '4',
 '8',
 '0',
 '0',
 '9',
 '2',
 '5',
 '1',
 '4',
 '1',
 '6',
 'c',
 '7',
 '5',
 '0',
 'a',
 'c',
 'a',
 '2',
 '3',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'E',
 'd',
 'i',
 't',
 'i',
 'n',
 'g',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '0',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '7',
 '2',
 '1',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 ...]

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features = 5000, stop_words='english')

In [64]:
vectors =cv.fit_transform(new_df['tags']).toarray()

AttributeError: 'list' object has no attribute 'lower'

In [65]:
vectors[0]

NameError: name 'vectors' is not defined